apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.0.9-alpine
          name: redis
          ports:
          - containerPort: 6379
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis://redis.default.svc.cluster.local
          image: ckw:latest
          imagePullPolicy: Never # required since we are using a local Docker registry
          name: web
          ports:
            - containerPort: 80
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: web
  name: web
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: web
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
  type: ClusterIP
