previews:
  generation: automatic

services:
  - type: web
    name: ckwatson-web
    runtime: docker

    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: ckwatson-redis
          property: connectionString

  - type: keyvalue
    name: ckwatson-redis
    ipAllowList: []
