apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  REDIS_PASSWORD: c3VwZXJzZWNyZXQK # base64 for 'supersecret' (replace with a real random value in production)
