apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: web
  name: web
spec:
  type: ClusterIP # For minikube, use 'minikube service web' to access externally
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: web
status:
  loadBalancer: {}
